# Generated by Django 2.2.5 on 2019-09-27 06:42

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190927_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='picture',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[book.models.validate_file_extension]),
        ),
    ]
